task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 5
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/cv/project/data/loco_processed/images/train
    ann_file: /root/cv/project/data/loco_processed/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8
  batch_size: 12
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /root/cv/project/data/loco_processed/images/val
    ann_file: /root/cv/project/data/loco_processed/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 8
  batch_size: 12
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
